### ISSUE TITLE
Calling a function

### ISSUE THREAD

**Issue by tetpsy** [audi/audi-ui#9]
I have installed and tested the ui kit with gulp and it all works nicely.

However for certain projects we need to use the compiled js file without gulp. 

I have compiled the audi-ui.min.js with gulp and would now like to use it with a standard front end website. 

The only problem is i cannot call or init a plugin function from outside of the web pack ui file.

I had to run the call from within the componentHandler function to get it to work, but this is not ideal for a permanent solution.

I see we must call a function like this
Nav.upgradeElements();

The call doesn't work if I run it from a separate index.html file. The file cannot find the variable Nav for example.

Can you help me understand how to call this from another file?

Do I need to call it differently 

Regards

**Comment by tetpsy** [comment]
I figured it out, one can not simply call it from an index.html file, i think i was supposed to call it in the src/index.js file and then compile with gulp.

This worked

**Comment by icholy** [comment]
Since it's a UMD module, you can access it using `window["audi-ui"]`.

Example:

``` js
window["audi-ui"].Spinner.upgradeElements();
```
